-e fix(linear-release): [SEMVER-123] Add linear link
[SEMVER-123](https://linear.app/rotate/issue/semver-123)

diff --git a/.husky/prepare-commit-msg b/.husky/prepare-commit-msg
--- a/.husky/prepare-commit-msg
+++ b/.husky/prepare-commit-msg
@@ -11,18 +11,21 @@ REGEX="\[${LINEAR_TEAM_PREFIX}-(\d+)\]"
 echo "COMMIT_MSG: $COMMIT_MSG"
 
 # Check for the regex match in the subject
-if echo "$COMMIT_MSG" | grep -qE "$REGEX"; then
-    # Extract the ID from the subject
-    ID=$(echo "$COMMIT_MSG" | grep -oE "$REGEX" | grep -oE '\d+')
+if grep -E "$REGEX" <<< "$COMMIT_MSG" &> /dev/null; then  # Suppress output and check exit code
+  # Extract the ID from the subject
+  ID=$(echo "$COMMIT_MSG" | grep -oE "$REGEX" | grep -oE '\d+')
 
-    # Create the markdown link
-    LOWER_PREFIX=$(echo "$LINEAR_TEAM_PREFIX" | tr '[:upper:]' '[:lower:]') # Convert to lowercase
-    LINK="[${LINEAR_TEAM_PREFIX}-${ID}](https://linear.app/rotate/issue/${LOWER_PREFIX}-${ID})"
+  # Create the markdown link
+  LOWER_PREFIX=$(echo "$LINEAR_TEAM_PREFIX" | tr '[:upper:]' '[:lower:]') # Convert to lowercase
+  LINK="[${LINEAR_TEAM_PREFIX}-${ID}](https://linear.app/rotate/issue/${LOWER_PREFIX}-${ID})"
 
-    echo "LINK: $LINK"
+  echo "LINK: $LINK"
 
-    # Append the link to the commit message
-    echo -e "$COMMIT_MSG\n\n$LINK" > "$COMMIT_MSG_FILE"
+  # Append the link to the commit message
+  echo -e "$COMMIT_MSG\n\n$LINK" > "$COMMIT_MSG_FILE"
 
-    echo "Appended the link to the commit message"
+  echo "Appended the link to the commit messages"
+else
+  echo "No matching SEMVER tag found in commit message."
+  exit 1  # Exit with non-zero code if no match
 fi
